# =============================================================================
# EasyShop Product Service Bootstrap Configuration
# =============================================================================
# This file points the service to the external Config Server.

spring:
  application:
    name: product-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    config:
      username: ${CONFIG_SERVER_USER:configuser}
      password: ${CONFIG_SERVER_PASSWORD:configpass}
      fail-fast: false
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
